# ~/ros2_ws/src/my_robot_bringup/config/gazebo_bridge.yaml

# Sim time
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# -------------------------
# EMILIOBOT bridges
# -------------------------

- ros_topic_name: "/emiliobot/joint_states"
  gz_topic_name: "/world/#PLACEHOLDER/model/emiliobot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/emiliobot/tf"
  gz_topic_name: "/model/emiliobot/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/emiliobot/cmd_vel"
  gz_topic_name: "/model/emiliobot/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# -------------------------
# MY_ROBOT bridges
# -------------------------

- ros_topic_name: "/my_robot/joint_states"
  gz_topic_name: "/world/#PLACEHOLDER/model/my_robot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/my_robot/tf"
  gz_topic_name: "/model/my_robot/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/my_robot/cmd_vel"
  gz_topic_name: "/model/my_robot/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# -------------------------
# POTATOBOT bridges
# -------------------------

- ros_topic_name: "/potatobot/joint_states"
  gz_topic_name: "/world/#PLACEHOLDER/model/my_robot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/potatobot/tf"
  gz_topic_name: "/model/potatobot/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/potatobot/cmd_vel"
  gz_topic_name: "/model/potatobot/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ


# =======================
#  EMILIOBOT CAMERA
# =======================
- ros_topic_name: "/emiliobot/camera/image_raw"
  gz_topic_name: "/world/#PLACEHOLDER/model/emiliobot/link/base_footprint/sensor/front_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/emiliobot/camera/camera_info"
  gz_topic_name: "/world/#PLACEHOLDER/model/emiliobot/link/base_footprint/sensor/front_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# =======================
#  MY_ROBOT CAMERA
# =======================
- ros_topic_name: "/my_robot/camera/image_raw"
  gz_topic_name: "/world/#PLACEHOLDER/model/my_robot/link/base_footprint/sensor/front_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/my_robot/camera/camera_info"
  gz_topic_name: "/world/#PLACEHOLDER/model/my_robot/link/base_footprint/sensor/front_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# =======================
#  POTATOBOT CAMERA
# =======================
- ros_topic_name: "/potatobot/camera/image_raw"
  gz_topic_name: "/world/#PLACEHOLDER/model/potatobot/link/base_footprint/sensor/front_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/my_robot/camera/camera_info"
  gz_topic_name: "/world/#PLACEHOLDER/model/potatobot/link/base_footprint/sensor/front_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS